#Site settings
#These are used to personalize the new site.
title: Home



#Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
#---
#redirect_from: "byt3bit.github.io/primesym"
#---

header_pages:
  - mimc.md
  - gmimc.md
  - starkad_poseidon.md
