#Site settings
#These are used to personalize the new site.
title: Home



#Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


header_pages:
  - mimc.md
  - gmimc.md
  - starkad_poseidon.md